"""
Render the eval table block in README.md from eval/results.json.

Why this exists:
- Numbers in the README must never drift from the actual eval output.
- Re-run `python -m scripts.evaluate` → `python -m scripts.render_readme`
  and the README's results table is regenerated in place.

The README has a marked block:
    <!-- EVAL_TABLE_START -->
    ... (regenerated content) ...
    <!-- EVAL_TABLE_END -->
Anything outside the markers is left untouched.
"""
import json
import os
import re
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README_PATH = os.path.join(PROJECT_ROOT, "README.md")
RESULTS_PATH = os.path.join(PROJECT_ROOT, "eval", "results.json")

START = "<!-- EVAL_TABLE_START -->"
END = "<!-- EVAL_TABLE_END -->"

LABELS = {
    "A_dense": "A. Dense only (semantic baseline)",
    "B_hybrid": "B. + BM25 + RRF",
    "C_hybrid_rerank": "C. + LLM rerank (full system)",
}


def fmt(x: float) -> str:
    return f"{x:.3f}"


def render_table(results: dict) -> str:
    cfg = results["config"]
    modes = results["modes"]
    k = cfg["k"]

    # Headline table
    lines = []
    lines.append(f"_Test set: {cfg['n_queries']} hand-labeled queries against `{cfg['repo']}` "
                 f"({cfg['n_chunks']} chunks). Embeddings: `{cfg['embedding_model']}`._")
    lines.append("")
    lines.append(f"| System | Hit Rate@{k} | MRR | Δ HR | Δ MRR |")
    lines.append("|---|---:|---:|---:|---:|")

    baseline = modes.get("A_dense")
    for key, label in LABELS.items():
        if key not in modes:
            continue
        m = modes[key]
        if key == "A_dense":
            d_hr, d_mrr = "—", "—"
        else:
            d_hr = f"{m['hit_rate_at_k'] - baseline['hit_rate_at_k']:+.3f}"
            d_mrr = f"{m['mrr'] - baseline['mrr']:+.3f}"
        lines.append(f"| {label} | **{fmt(m['hit_rate_at_k'])}** | **{fmt(m['mrr'])}** | {d_hr} | {d_mrr} |")

    # Per-kind breakdown
    lines.append("")
    lines.append(f"**Breakdown by query kind** (HR@{k} / MRR):")
    lines.append("")
    lines.append("| System | Explicit-name queries | Fuzzy/conceptual queries |")
    lines.append("|---|---|---|")
    for key, label in LABELS.items():
        if key not in modes:
            continue
        bk = modes[key].get("by_kind", {})
        ex = bk.get("explicit", {})
        fz = bk.get("fuzzy", {})
        ex_str = f"{fmt(ex.get('hit_rate_at_k', 0))} / {fmt(ex.get('mrr', 0))}"
        fz_str = f"{fmt(fz.get('hit_rate_at_k', 0))} / {fmt(fz.get('mrr', 0))}"
        lines.append(f"| {label} | {ex_str} | {fz_str} |")

    return "\n".join(lines)


def main():
    if not os.path.exists(RESULTS_PATH):
        sys.exit(f"No eval results at {RESULTS_PATH}. Run `python -m scripts.evaluate` first.")

    with open(RESULTS_PATH) as f:
        results = json.load(f)

    with open(README_PATH) as f:
        readme = f.read()

    table = render_table(results)
    block = f"{START}\n<!-- Auto-generated by scripts/render_readme.py — do not edit by hand -->\n{table}\n{END}"

    if START not in readme or END not in readme:
        sys.exit(f"README is missing {START} ... {END} markers. Add them where you want the table.")

    new_readme = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        block,
        readme,
        flags=re.DOTALL,
    )

    with open(README_PATH, "w") as f:
        f.write(new_readme)

    print(f"README updated: numbers from {RESULTS_PATH} written into {README_PATH}")


if __name__ == "__main__":
    main()
